CREATE PROCEDURE [dbo].[DepartamentoEliminar]
	@ID int = null 
	
AS
BEGIN
    SET NOCOUNT ON
	BEGIN TRANSACTION TRASA

	BEGIN TRY 
	
	    DELETE FROM  Departamentos	
		WHERE Id_Departamento = @ID
	
	  
	COMMIT TRANSACTION TRASA
	
	 SELECT 0 AS CodeError, '' AS MsgError

	END TRY 

	BEGIN CATCH 
	    SELECT 
		  ERROR_NUMBER() AS CodeError
		, ERROR_MESSAGE() AS MsgError

		ROLLBACK TRANSACTION TRASA
	END  CATCH

END